/*
 * GENERATED FILE. DO NOT EDIT.
 * This file is generated by Eflatun.SceneReference package.
 */

#pragma warning disable

using System.Collections.Generic;

namespace Eflatun.SceneReference
{
    public static partial class Map
    {
        static Map()
        {
            SceneGuidToScenePath = new Dictionary<string, string>
            {
                {"45ac7250dffb26f4e84eda01a52b8b19", "Assets/Scenes/SceneA.unity"},
                {"c5d794d51a8a22c46a17330344e5d1f5", "Assets/Scenes/SceneB.unity"},
                {"50ccd0f8666b55544ac0f21398ad9535", "Assets/Scenes Folder 2/SceneC.unity"},
            };
        }
    }
}
